server:
  port: 8081

spring:
  config:
    import: "optional:classpath:application-secrets.properties"
  application:
    name: resale-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/resale_market_db
    username: postgres
    password: Mementomori
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
