server:
  port: 8081
vnpay:
  tmn_code: I9F2C8N0
  hash_secret: X8IGIHJ6ZAFACMYLOKVI5E9L5MH7WGVP
  api_url: "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
  return_url: "http://localhost:8081/api/payment/vnpay-callback"
app:
  frontend:
    url: http://localhost:5173
# Custom property for your GCS bucket
gcp:
  bucket:
    name: resale-ai-outputs-232931

spring:
  codec:
    max-in-memory-size: 10MB
  config:
    import: "optional:classpath:application-secrets.properties"
  application:
    name: resale-backend
  ai:
    vertex:
      ai:
        gemini:
          project-id: project-e3f1272c-e056-48d4-8a9
          location: us-central1

  cloud:
    gcp:
      # Workload Identity doesn't need 'credentials.location'
      # It uses Application Default Credentials (ADC) automatically
      storage:
        enabled: true
      core:
        project-id: project-e3f1272c-e056-48d4-8a9

  datasource:
    url: jdbc:postgresql://localhost:5432/resale_market_db
    username: postgres
    password: Mementomori
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: true